### ISSUE TITLE
App update related notifications shouldn't be in the home tab 

### ISSUE THREAD

**Issue by q-omar** [Salam-Labs/Salam-App-Issues#12]
Instead move them to the settings tab, and possibly have a little red notification badge that says app is updated. 

![IMG_2258](https://user-images.githubusercontent.com/25255233/181924896-21c32f15-190a-4efa-888f-e6969b1edf3c.jpeg)

____ 
**Phone Model:** iPhone Xr
**Software version:** 15.5
**Salam App version:** 0.5.0 (7)

**Comment by Tr1d3nt** [comment]
Will change "App Update" to "What's New" as a way to show the new features added.

**Comment by Tr1d3nt** [comment]
closing for now. Will revisit in near future to move to settings once more sections added to home.
