### ISSUE TITLE
99 Names, Al-Mutakabbir

### ISSUE THREAD

**Issue by Treestars76** [Salam-Labs/Salam-App-Issues#6]
The tile for this name is shorter than every other tile?
![IMG_0870](https://user-images.githubusercontent.com/108589404/177074766-a5b70246-4a7a-4089-b91a-475aecd653da.png)
![IMG_0871](https://user-images.githubusercontent.com/108589404/177074794-0b3dccb9-50e6-44ed-bd83-bd8ba4100f95.png)

**Comment by saad197** [comment]
The tiles were removed completely for list. Ty.
