### ISSUE TITLE
Qibla Compass is ALWAYS active

### ISSUE THREAD

**Issue by Treestars76** [Salam-Labs/Salam-App-Issues#8]
The app will vibrate when facing the qibla no matter where the user is in the app, I have yet to find a page in the app where my phone does not vibrate when turned towards the Qibla.

**Comment by q-omar** [comment]
I also have this issue 

**Phone Model:** iPhone Xr
**Software version:** 15.5
**Salam App version:** 0.5.0 (7)

**Comment by saad197** [comment]
This will be fixed in the upcoming build.
