### ISSUE TITLE
The tafsir button can likely be integrated into the Quran button 

### ISSUE THREAD

**Issue by q-omar** [Salam-Labs/Salam-App-Issues#9]
https://user-images.githubusercontent.com/25255233/181923545-03627859-60e9-4eb2-b169-ff12146f68ef.mov

For example rather than having an individual button have the Quran button instead say Quran (with Tafsir)

____

**Phone Model:** iPhone Xr
**Software version:** 15.5
**Salam App version:** 0.5.0 (7)

**Comment by saad197** [comment]
Thank you, we have a discrete tafsir module now in the upcoming build, so it will launch with that button.
